### ISSUE TITLE
Standings Order

### ISSUE THREAD

**Issue by stirlingv** [stirlingv/dcstreethockey#1]
Standings should be calculated via 2pts for a win and 1pt for a tie. Current ordering leaves potential for bugs... I.E. 5-5 (10pts) is ranked higher than a 4-3-3 (11pts). Need to assign points for display.

**Comment by scottdmoore** [comment]
Have you done this yet or can I work it?

**Comment by stirlingv** [comment]
@scottdmoore Hoff did this for the teams, but similar logic doesn't work for the player standings. Could use a second set of eyes to help with that one!
